/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-06-29 at 16:25:41 UTC 
 * Modify at your own risk.
 */

package com.tudor.ctm.ui.shared.cloudtaskendpoint;

/**
 * Service definition for Cloudtaskendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CloudtaskendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Cloudtaskendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ctm-tudor.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "cloudtaskendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Cloudtaskendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Cloudtaskendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCloudTask".
   *
   * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting any
   * optional parameters, call the {@link GetCloudTask#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetCloudTask getCloudTask(java.lang.Long id) throws java.io.IOException {
    GetCloudTask result = new GetCloudTask(id);
    initialize(result);
    return result;
  }

  public class GetCloudTask extends CloudtaskendpointRequest<com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask> {

    private static final String REST_PATH = "cloudtask/{id}";

    /**
     * Create a request for the method "getCloudTask".
     *
     * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting
     * any optional parameters, call the {@link GetCloudTask#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCloudTask#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCloudTask(java.lang.Long id) {
      super(Cloudtaskendpoint.this, "GET", REST_PATH, null, com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCloudTask setAlt(java.lang.String alt) {
      return (GetCloudTask) super.setAlt(alt);
    }

    @Override
    public GetCloudTask setFields(java.lang.String fields) {
      return (GetCloudTask) super.setFields(fields);
    }

    @Override
    public GetCloudTask setKey(java.lang.String key) {
      return (GetCloudTask) super.setKey(key);
    }

    @Override
    public GetCloudTask setOauthToken(java.lang.String oauthToken) {
      return (GetCloudTask) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCloudTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCloudTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCloudTask setQuotaUser(java.lang.String quotaUser) {
      return (GetCloudTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCloudTask setUserIp(java.lang.String userIp) {
      return (GetCloudTask) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCloudTask setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCloudTask set(String parameterName, Object value) {
      return (GetCloudTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCloudTask".
   *
   * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting any
   * optional parameters, call the {@link InsertCloudTask#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask}
   * @return the request
   */
  public InsertCloudTask insertCloudTask(com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask content) throws java.io.IOException {
    InsertCloudTask result = new InsertCloudTask(content);
    initialize(result);
    return result;
  }

  public class InsertCloudTask extends CloudtaskendpointRequest<com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask> {

    private static final String REST_PATH = "cloudtask";

    /**
     * Create a request for the method "insertCloudTask".
     *
     * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting
     * any optional parameters, call the {@link InsertCloudTask#execute()} method to invoke the remote
     * operation. <p> {@link InsertCloudTask#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask}
     * @since 1.13
     */
    protected InsertCloudTask(com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask content) {
      super(Cloudtaskendpoint.this, "POST", REST_PATH, content, com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask.class);
    }

    @Override
    public InsertCloudTask setAlt(java.lang.String alt) {
      return (InsertCloudTask) super.setAlt(alt);
    }

    @Override
    public InsertCloudTask setFields(java.lang.String fields) {
      return (InsertCloudTask) super.setFields(fields);
    }

    @Override
    public InsertCloudTask setKey(java.lang.String key) {
      return (InsertCloudTask) super.setKey(key);
    }

    @Override
    public InsertCloudTask setOauthToken(java.lang.String oauthToken) {
      return (InsertCloudTask) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCloudTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCloudTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCloudTask setQuotaUser(java.lang.String quotaUser) {
      return (InsertCloudTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCloudTask setUserIp(java.lang.String userIp) {
      return (InsertCloudTask) super.setUserIp(userIp);
    }

    @Override
    public InsertCloudTask set(String parameterName, Object value) {
      return (InsertCloudTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCloudTask".
   *
   * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting any
   * optional parameters, call the {@link ListCloudTask#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCloudTask listCloudTask() throws java.io.IOException {
    ListCloudTask result = new ListCloudTask();
    initialize(result);
    return result;
  }

  public class ListCloudTask extends CloudtaskendpointRequest<com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CollectionResponseCloudTask> {

    private static final String REST_PATH = "cloudtask";

    /**
     * Create a request for the method "listCloudTask".
     *
     * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting
     * any optional parameters, call the {@link ListCloudTask#execute()} method to invoke the remote
     * operation. <p> {@link ListCloudTask#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCloudTask() {
      super(Cloudtaskendpoint.this, "GET", REST_PATH, null, com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CollectionResponseCloudTask.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCloudTask setAlt(java.lang.String alt) {
      return (ListCloudTask) super.setAlt(alt);
    }

    @Override
    public ListCloudTask setFields(java.lang.String fields) {
      return (ListCloudTask) super.setFields(fields);
    }

    @Override
    public ListCloudTask setKey(java.lang.String key) {
      return (ListCloudTask) super.setKey(key);
    }

    @Override
    public ListCloudTask setOauthToken(java.lang.String oauthToken) {
      return (ListCloudTask) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCloudTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCloudTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCloudTask setQuotaUser(java.lang.String quotaUser) {
      return (ListCloudTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCloudTask setUserIp(java.lang.String userIp) {
      return (ListCloudTask) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCloudTask setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCloudTask setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCloudTask set(String parameterName, Object value) {
      return (ListCloudTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCloudTask".
   *
   * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting any
   * optional parameters, call the {@link RemoveCloudTask#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCloudTask removeCloudTask(java.lang.Long id) throws java.io.IOException {
    RemoveCloudTask result = new RemoveCloudTask(id);
    initialize(result);
    return result;
  }

  public class RemoveCloudTask extends CloudtaskendpointRequest<com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask> {

    private static final String REST_PATH = "cloudtask/{id}";

    /**
     * Create a request for the method "removeCloudTask".
     *
     * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting
     * any optional parameters, call the {@link RemoveCloudTask#execute()} method to invoke the remote
     * operation. <p> {@link RemoveCloudTask#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCloudTask(java.lang.Long id) {
      super(Cloudtaskendpoint.this, "DELETE", REST_PATH, null, com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCloudTask setAlt(java.lang.String alt) {
      return (RemoveCloudTask) super.setAlt(alt);
    }

    @Override
    public RemoveCloudTask setFields(java.lang.String fields) {
      return (RemoveCloudTask) super.setFields(fields);
    }

    @Override
    public RemoveCloudTask setKey(java.lang.String key) {
      return (RemoveCloudTask) super.setKey(key);
    }

    @Override
    public RemoveCloudTask setOauthToken(java.lang.String oauthToken) {
      return (RemoveCloudTask) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCloudTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCloudTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCloudTask setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCloudTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCloudTask setUserIp(java.lang.String userIp) {
      return (RemoveCloudTask) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCloudTask setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCloudTask set(String parameterName, Object value) {
      return (RemoveCloudTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCloudTask".
   *
   * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting any
   * optional parameters, call the {@link UpdateCloudTask#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask}
   * @return the request
   */
  public UpdateCloudTask updateCloudTask(com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask content) throws java.io.IOException {
    UpdateCloudTask result = new UpdateCloudTask(content);
    initialize(result);
    return result;
  }

  public class UpdateCloudTask extends CloudtaskendpointRequest<com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask> {

    private static final String REST_PATH = "cloudtask";

    /**
     * Create a request for the method "updateCloudTask".
     *
     * This request holds the parameters needed by the the cloudtaskendpoint server.  After setting
     * any optional parameters, call the {@link UpdateCloudTask#execute()} method to invoke the remote
     * operation. <p> {@link UpdateCloudTask#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask}
     * @since 1.13
     */
    protected UpdateCloudTask(com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask content) {
      super(Cloudtaskendpoint.this, "PUT", REST_PATH, content, com.tudor.ctm.ui.shared.cloudtaskendpoint.model.CloudTask.class);
    }

    @Override
    public UpdateCloudTask setAlt(java.lang.String alt) {
      return (UpdateCloudTask) super.setAlt(alt);
    }

    @Override
    public UpdateCloudTask setFields(java.lang.String fields) {
      return (UpdateCloudTask) super.setFields(fields);
    }

    @Override
    public UpdateCloudTask setKey(java.lang.String key) {
      return (UpdateCloudTask) super.setKey(key);
    }

    @Override
    public UpdateCloudTask setOauthToken(java.lang.String oauthToken) {
      return (UpdateCloudTask) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCloudTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCloudTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCloudTask setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCloudTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCloudTask setUserIp(java.lang.String userIp) {
      return (UpdateCloudTask) super.setUserIp(userIp);
    }

    @Override
    public UpdateCloudTask set(String parameterName, Object value) {
      return (UpdateCloudTask) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Cloudtaskendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Cloudtaskendpoint}. */
    @Override
    public Cloudtaskendpoint build() {
      return new Cloudtaskendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CloudtaskendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCloudtaskendpointRequestInitializer(
        CloudtaskendpointRequestInitializer cloudtaskendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(cloudtaskendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
