/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-13 at 15:15:16 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudprojectendpoint.model;

import com.google.api.services.clouduserendpoint.model.CloudUser;

/**
 * Model definition for CloudProject.
 * 
 * <p>
 * This is the Java data model class that specifies how to parse/serialize into
 * the JSON that is transmitted over HTTP when working with the . For a detailed
 * explanation see: <a
 * href="http://code.google.com/p/google-http-java-client/wiki/JSON"
 * >http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 * 
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CloudProject extends com.google.api.client.json.GenericJson {

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	@com.google.api.client.json.JsonString
	private java.lang.Long id;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.util.List<CloudUser> members;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private java.lang.String name;

	/**
	 * The value may be {@code null}.
	 */
	@com.google.api.client.util.Key
	private CloudUser owner;

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            id or {@code null} for none
	 */
	public CloudProject setId(java.lang.Long id) {
		this.id = id;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.util.List<CloudUser> getMembers() {
		return members;
	}

	/**
	 * @param members
	 *            members or {@code null} for none
	 */
	public CloudProject setMembers(java.util.List<CloudUser> members) {
		this.members = members;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * @param name
	 *            name or {@code null} for none
	 */
	public CloudProject setName(java.lang.String name) {
		this.name = name;
		return this;
	}

	/**
	 * @return value or {@code null} for none
	 */
	public CloudUser getOwner() {
		return owner;
	}

	/**
	 * @param owner
	 *            owner or {@code null} for none
	 */
	public CloudProject setOwner(CloudUser owner) {
		this.owner = owner;
		return this;
	}

	@Override
	public CloudProject set(String fieldName, Object value) {
		return (CloudProject) super.set(fieldName, value);
	}

	@Override
	public CloudProject clone() {
		return (CloudProject) super.clone();
	}

	@Override
	public String toString() {
		return "CloudProject [id=" + id + ", name=" + name + "]";
	}

	public static class Builder {
		private java.lang.Long id;
		private java.lang.String name;

		public Builder id(java.lang.Long id) {
			this.id = id;
			return this;
		}

		public Builder name(java.lang.String name) {
			this.name = name;
			return this;
		}

		public CloudProject build() {
			return new CloudProject(this);
		}
	}

	private CloudProject(Builder builder) {
		this.id = builder.id;
		this.name = builder.name;
	}

	public CloudProject() {
	}
}
