/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-13 at 15:15:16 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.cloudprojectendpoint;

/**
 * Service definition for Cloudprojectendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CloudprojectendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Cloudprojectendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ctm-tudor.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "cloudprojectendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Cloudprojectendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Cloudprojectendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCloudProject".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link GetCloudProject#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetCloudProject getCloudProject(java.lang.Long id) throws java.io.IOException {
    GetCloudProject result = new GetCloudProject(id);
    initialize(result);
    return result;
  }

  public class GetCloudProject extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CloudProject> {

    private static final String REST_PATH = "getcloudproject";

    /**
     * Create a request for the method "getCloudProject".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link GetCloudProject#execute()} method to invoke the remote
     * operation. <p> {@link GetCloudProject#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCloudProject(java.lang.Long id) {
      super(Cloudprojectendpoint.this, "GET", REST_PATH, null, com.google.api.services.cloudprojectendpoint.model.CloudProject.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCloudProject setAlt(java.lang.String alt) {
      return (GetCloudProject) super.setAlt(alt);
    }

    @Override
    public GetCloudProject setFields(java.lang.String fields) {
      return (GetCloudProject) super.setFields(fields);
    }

    @Override
    public GetCloudProject setKey(java.lang.String key) {
      return (GetCloudProject) super.setKey(key);
    }

    @Override
    public GetCloudProject setOauthToken(java.lang.String oauthToken) {
      return (GetCloudProject) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCloudProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCloudProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCloudProject setQuotaUser(java.lang.String quotaUser) {
      return (GetCloudProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCloudProject setUserIp(java.lang.String userIp) {
      return (GetCloudProject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCloudProject setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCloudProject set(String parameterName, Object value) {
      return (GetCloudProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getuserprojects".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link Getuserprojects#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudUser}
   * @return the request
   */
  public Getuserprojects getuserprojects(com.google.api.services.cloudprojectendpoint.model.CloudUser content) throws java.io.IOException {
    Getuserprojects result = new Getuserprojects(content);
    initialize(result);
    return result;
  }

  public class Getuserprojects extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CloudProjectCollection> {

    private static final String REST_PATH = "getuserprojects";

    /**
     * Create a request for the method "getuserprojects".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link Getuserprojects#execute()} method to invoke the remote
     * operation. <p> {@link Getuserprojects#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudUser}
     * @since 1.13
     */
    protected Getuserprojects(com.google.api.services.cloudprojectendpoint.model.CloudUser content) {
      super(Cloudprojectendpoint.this, "POST", REST_PATH, content, com.google.api.services.cloudprojectendpoint.model.CloudProjectCollection.class);
    }

    @Override
    public Getuserprojects setAlt(java.lang.String alt) {
      return (Getuserprojects) super.setAlt(alt);
    }

    @Override
    public Getuserprojects setFields(java.lang.String fields) {
      return (Getuserprojects) super.setFields(fields);
    }

    @Override
    public Getuserprojects setKey(java.lang.String key) {
      return (Getuserprojects) super.setKey(key);
    }

    @Override
    public Getuserprojects setOauthToken(java.lang.String oauthToken) {
      return (Getuserprojects) super.setOauthToken(oauthToken);
    }

    @Override
    public Getuserprojects setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getuserprojects) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getuserprojects setQuotaUser(java.lang.String quotaUser) {
      return (Getuserprojects) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getuserprojects setUserIp(java.lang.String userIp) {
      return (Getuserprojects) super.setUserIp(userIp);
    }

    @Override
    public Getuserprojects set(String parameterName, Object value) {
      return (Getuserprojects) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getuserprojectsbyemail".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link Getuserprojectsbyemail#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @return the request
   */
  public Getuserprojectsbyemail getuserprojectsbyemail(java.lang.String email) throws java.io.IOException {
    Getuserprojectsbyemail result = new Getuserprojectsbyemail(email);
    initialize(result);
    return result;
  }

  public class Getuserprojectsbyemail extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CloudProjectCollection> {

    private static final String REST_PATH = "getuserprojectsbyemail";

    /**
     * Create a request for the method "getuserprojectsbyemail".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link Getuserprojectsbyemail#execute()} method to invoke the
     * remote operation. <p> {@link Getuserprojectsbyemail#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected Getuserprojectsbyemail(java.lang.String email) {
      super(Cloudprojectendpoint.this, "GET", REST_PATH, null, com.google.api.services.cloudprojectendpoint.model.CloudProjectCollection.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getuserprojectsbyemail setAlt(java.lang.String alt) {
      return (Getuserprojectsbyemail) super.setAlt(alt);
    }

    @Override
    public Getuserprojectsbyemail setFields(java.lang.String fields) {
      return (Getuserprojectsbyemail) super.setFields(fields);
    }

    @Override
    public Getuserprojectsbyemail setKey(java.lang.String key) {
      return (Getuserprojectsbyemail) super.setKey(key);
    }

    @Override
    public Getuserprojectsbyemail setOauthToken(java.lang.String oauthToken) {
      return (Getuserprojectsbyemail) super.setOauthToken(oauthToken);
    }

    @Override
    public Getuserprojectsbyemail setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getuserprojectsbyemail) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getuserprojectsbyemail setQuotaUser(java.lang.String quotaUser) {
      return (Getuserprojectsbyemail) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getuserprojectsbyemail setUserIp(java.lang.String userIp) {
      return (Getuserprojectsbyemail) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public Getuserprojectsbyemail setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @Override
    public Getuserprojectsbyemail set(String parameterName, Object value) {
      return (Getuserprojectsbyemail) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCloudProject".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link InsertCloudProject#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudProject}
   * @return the request
   */
  public InsertCloudProject insertCloudProject(com.google.api.services.cloudprojectendpoint.model.CloudProject content) throws java.io.IOException {
    InsertCloudProject result = new InsertCloudProject(content);
    initialize(result);
    return result;
  }

  public class InsertCloudProject extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CloudProject> {

    private static final String REST_PATH = "insertcloudproject";

    /**
     * Create a request for the method "insertCloudProject".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link InsertCloudProject#execute()} method to invoke the
     * remote operation. <p> {@link InsertCloudProject#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudProject}
     * @since 1.13
     */
    protected InsertCloudProject(com.google.api.services.cloudprojectendpoint.model.CloudProject content) {
      super(Cloudprojectendpoint.this, "POST", REST_PATH, content, com.google.api.services.cloudprojectendpoint.model.CloudProject.class);
    }

    @Override
    public InsertCloudProject setAlt(java.lang.String alt) {
      return (InsertCloudProject) super.setAlt(alt);
    }

    @Override
    public InsertCloudProject setFields(java.lang.String fields) {
      return (InsertCloudProject) super.setFields(fields);
    }

    @Override
    public InsertCloudProject setKey(java.lang.String key) {
      return (InsertCloudProject) super.setKey(key);
    }

    @Override
    public InsertCloudProject setOauthToken(java.lang.String oauthToken) {
      return (InsertCloudProject) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCloudProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCloudProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCloudProject setQuotaUser(java.lang.String quotaUser) {
      return (InsertCloudProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCloudProject setUserIp(java.lang.String userIp) {
      return (InsertCloudProject) super.setUserIp(userIp);
    }

    @Override
    public InsertCloudProject set(String parameterName, Object value) {
      return (InsertCloudProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCloudProject".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link ListCloudProject#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCloudProject listCloudProject() throws java.io.IOException {
    ListCloudProject result = new ListCloudProject();
    initialize(result);
    return result;
  }

  public class ListCloudProject extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CollectionResponseCloudProject> {

    private static final String REST_PATH = "cloudproject";

    /**
     * Create a request for the method "listCloudProject".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link ListCloudProject#execute()} method to invoke the
     * remote operation. <p> {@link ListCloudProject#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCloudProject() {
      super(Cloudprojectendpoint.this, "GET", REST_PATH, null, com.google.api.services.cloudprojectendpoint.model.CollectionResponseCloudProject.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCloudProject setAlt(java.lang.String alt) {
      return (ListCloudProject) super.setAlt(alt);
    }

    @Override
    public ListCloudProject setFields(java.lang.String fields) {
      return (ListCloudProject) super.setFields(fields);
    }

    @Override
    public ListCloudProject setKey(java.lang.String key) {
      return (ListCloudProject) super.setKey(key);
    }

    @Override
    public ListCloudProject setOauthToken(java.lang.String oauthToken) {
      return (ListCloudProject) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCloudProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCloudProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCloudProject setQuotaUser(java.lang.String quotaUser) {
      return (ListCloudProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCloudProject setUserIp(java.lang.String userIp) {
      return (ListCloudProject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCloudProject setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCloudProject setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCloudProject set(String parameterName, Object value) {
      return (ListCloudProject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCloudProject".
   *
   * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
   * any optional parameters, call the {@link UpdateCloudProject#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudProject}
   * @return the request
   */
  public UpdateCloudProject updateCloudProject(com.google.api.services.cloudprojectendpoint.model.CloudProject content) throws java.io.IOException {
    UpdateCloudProject result = new UpdateCloudProject(content);
    initialize(result);
    return result;
  }

  public class UpdateCloudProject extends CloudprojectendpointRequest<com.google.api.services.cloudprojectendpoint.model.CloudProject> {

    private static final String REST_PATH = "updatecloudproject";

    /**
     * Create a request for the method "updateCloudProject".
     *
     * This request holds the parameters needed by the the cloudprojectendpoint server.  After setting
     * any optional parameters, call the {@link UpdateCloudProject#execute()} method to invoke the
     * remote operation. <p> {@link UpdateCloudProject#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.cloudprojectendpoint.model.CloudProject}
     * @since 1.13
     */
    protected UpdateCloudProject(com.google.api.services.cloudprojectendpoint.model.CloudProject content) {
      super(Cloudprojectendpoint.this, "POST", REST_PATH, content, com.google.api.services.cloudprojectendpoint.model.CloudProject.class);
    }

    @Override
    public UpdateCloudProject setAlt(java.lang.String alt) {
      return (UpdateCloudProject) super.setAlt(alt);
    }

    @Override
    public UpdateCloudProject setFields(java.lang.String fields) {
      return (UpdateCloudProject) super.setFields(fields);
    }

    @Override
    public UpdateCloudProject setKey(java.lang.String key) {
      return (UpdateCloudProject) super.setKey(key);
    }

    @Override
    public UpdateCloudProject setOauthToken(java.lang.String oauthToken) {
      return (UpdateCloudProject) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCloudProject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCloudProject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCloudProject setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCloudProject) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCloudProject setUserIp(java.lang.String userIp) {
      return (UpdateCloudProject) super.setUserIp(userIp);
    }

    @Override
    public UpdateCloudProject set(String parameterName, Object value) {
      return (UpdateCloudProject) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Cloudprojectendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Cloudprojectendpoint}. */
    @Override
    public Cloudprojectendpoint build() {
      return new Cloudprojectendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CloudprojectendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCloudprojectendpointRequestInitializer(
        CloudprojectendpointRequestInitializer cloudprojectendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(cloudprojectendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
